/*
 * AsiaHorse Umbra / ROBOBLOQ USBFAN - SignalRGB plugin
 * USB VID: 0x1A86
 * USB PID: 0xFE05
 *
 * Reverse-engineered from USBPcap traffic generated by the official
 * AsiaHorse software.
 *
 * Native commands use:
 *   52 42 [length] 00 [body...] [checksum]
 *
 * Direct RGB frames use:
 *   88 [packet count] [packet index] [20 x RGB] [checksum]
 *
 * The current configuration uses six 64-byte packets per frame, providing
 * 120 RGB slots. Ten physical ports are mapped to 11 slots each (110 slots),
 * leaving the final 10 slots as black padding.
 *
 * The additive checksum is:
 *   sum(packet bytes before checksum) & 0xFF
 *
 * FE05 selector 0x01 is the controller's native Rainbow effect and is not
 * used for live SignalRGB rendering. Live rendering uses the 0x88 direct
 * RGB stream.
 */

/* global debugMode, debugLog */

export function Name() { return "AsiaHorse Umbra ARGB Hub"; }
export function VendorId() { return 0x1A86; }
export function ProductId() { return 0xFE05; }
export function Publisher() { return "Huynh Mai"; }
export function Documentation() { return "troubleshooting/other"; }
export function Type() { return "hid"; }
export function SubdeviceController() { return true; }

export function Size() { return [10, 1]; }
export function DefaultPosition() { return [0, 0]; }
export function DefaultScale() { return 8.0; }

export function ImageUrl() {
    return "https://raw.githubusercontent.com/maihcx/AsiaHorse-Umbra-ARGB-Hub-SignalRGB-Plugin/main/Images/AsiaHorseUmbra.png";
}

export function ControllableParameters() {
    return [
        {
            property: "debugMode",
            group: "lighting",
            label: "Debug Mode",
            type: "combobox",
            values: [
                "Live",
                "Native Rainbow Test",
                "Test Pattern (solid red)"
            ],
            default: "Live"
        },
        {
            property: "debugLog",
            group: "lighting",
            label: "Log protocol activity to console",
            type: "boolean",
            default: 0
        }
    ];
}


const CHANNEL_COUNT = 10;

/*
 * SignalRGB components may declare different LED counts, but each physical
 * hub port occupies a fixed 11-slot region in the direct RGB stream.
 * LedCount() is therefore used only as the source component size and never
 * to calculate physical port offsets.
 */
const LED_LIMIT_PER_CHANNEL = 120;
const DIRECT_PORT_COUNT = 10;
const DIRECT_SLOTS_PER_PORT = 11;

const DIRECT_STREAM_PACKET_COUNT = 6;
const DIRECT_STREAM_LEDS_PER_PACKET = 20;
const DIRECT_STREAM_LED_LIMIT =
    DIRECT_STREAM_PACKET_COUNT *
    DIRECT_STREAM_LEDS_PER_PACKET;

const DIRECT_MAPPED_LED_COUNT =
    DIRECT_PORT_COUNT *
    DIRECT_SLOTS_PER_PORT;

const CHANNELS = [
    "ARGB Port 01",
    "ARGB Port 02",
    "ARGB Port 03",
    "ARGB Port 04",
    "ARGB Port 05",
    "ARGB Port 06",
    "ARGB Port 07",
    "ARGB Port 08",
    "ARGB Port 09",
    "ARGB Port 10"
];


const MODE_SOLID = 0x00;
const MODE_NATIVE_RAINBOW = 0x01;
const PALETTE_SLOTS = 12;

/*
 * RGBY palette observed with FE05 selector 0x01. The controller animates
 * this palette internally as its native Rainbow effect.
 */
const CAPTURED_NATIVE_RAINBOW = [
    [255,   0,   0],
    [  0, 255,   0],
    [  0,   0, 255],
    [255, 255,   0],

    [255,   0,   0],
    [  0, 255,   0],
    [  0,   0, 255],
    [255, 255,   0],

    [255,   0,   0],
    [  0, 255,   0],
    [  0,   0, 255],
    [255, 255,   0]
];

/*
 * Exact FE05 profile body prefix observed in the capture.
 *
 * body[2] = physical port index
 * body[9] = selector
 * 12 RGB palette entries are appended after this prefix.
 */
const PORT_PROFILE_PREFIX = [
    0x03, 0xFD,
    0x00,
    0x04,
    0x01, 0x01, 0x01, 0x01, 0x01,
    0x00,
    0x03, 0x03, 0x03,
    0x01, 0x01, 0x01,
    0x99, 0x99, 0x99
];


let frameCounter = 0;
let lastDebugMode = "";
let nativeLastProfiles = [];
let nativePortInitialized = [];


export function Validate(endpoint) {
    return endpoint.interface === 0 &&
           endpoint.usage_page === 0xFF00 &&
           endpoint.usage === 0x0001;
}

export function LedNames() {
    return [];
}

export function LedPositions() {
    return [];
}

export function Initialize() {
    setupChannels();

    frameCounter = 0;
    lastDebugMode = getCurrentDebugMode();

    invalidateNativeProfileCache();

    /*
     * Startup sequence observed from the official application.
     *
     * FB 64 = brightness 100%
     * FD 01 = enable software / independently controlled lighting mode
     */
    sendNativeCommand([0xFB, 0x64]);
    device.pause(10);

    enterSoftwareControlMode();

    if (lastDebugMode === "Live") {
        sendDirectRgbFrame();
    } else {
        renderNativeDebugMode(true);
    }

    if (isDebugLoggingEnabled()) {
        device.log(
            "[AsiaHorse] Initialized. Direct RGB capacity=" +
            DIRECT_STREAM_LED_LIMIT +
            " slots, mapped=" +
            DIRECT_MAPPED_LED_COUNT +
            " (" +
            DIRECT_PORT_COUNT +
            " ports x " +
            DIRECT_SLOTS_PER_PORT +
            "), transport=" +
            DIRECT_STREAM_PACKET_COUNT +
            " packets x " +
            DIRECT_STREAM_LEDS_PER_PACKET +
            " RGB)."
        );
    }
}

export function Render() {
    frameCounter++;

    const currentMode = getCurrentDebugMode();

    /*
     * A mode change must explicitly re-enter software control mode and
     * invalidate cached native profiles.
     */
    if (currentMode !== lastDebugMode) {
        lastDebugMode = currentMode;

        invalidateNativeProfileCache();
        enterSoftwareControlMode();

        if (isDebugLoggingEnabled()) {
            device.log(
                "[AsiaHorse] Debug mode changed to: " +
                currentMode
            );
        }
    }

    /*
     * Stream one complete direct RGB frame on every SignalRGB render.
     * Native keep-alive commands are not inserted into the 0x88 stream.
     */
    if (currentMode === "Live") {
        sendDirectRgbFrame();
        return;
    }

    /*
     * Native debug modes only need their FE05 profiles resent when changed.
     */
    renderNativeDebugMode(false);

    /*
     * Native mode keep-alive observed from the official application.
     */
    if ((frameCounter % 30) === 0) {
        sendNativeKeepAlive();
    }
}

export function Shutdown(/* SystemSuspending */) {
    // Preserve the last visible state.
}


/*
 * SignalRGB user-control callback.
 */
export function ondebugModeChanged() {
    lastDebugMode = getCurrentDebugMode();

    invalidateNativeProfileCache();
    enterSoftwareControlMode();

    if (lastDebugMode === "Live") {
        sendDirectRgbFrame();
    } else {
        renderNativeDebugMode(true);
    }
}

export function ondebugLogChanged() {
}


function setupChannels() {
    /*
     * Six packets provide 120 RGB slots for the complete direct RGB frame.
     */
    device.SetLedLimit(DIRECT_STREAM_LED_LIMIT);

    /*
     * Remove channels left behind by hot-reloaded older plugin versions.
     */
    for (let i = 1; i <= CHANNEL_COUNT; i++) {
        const legacyName = "ARGB Port " + i;
        const currentName = "ARGB Port " + String(i).padStart(2, "0");

        try {
            device.removeChannel(legacyName);
        } catch (e) {
            // Ignore missing channels.
        }

        try {
            device.removeChannel(currentName);
        } catch (e) {
            // Ignore missing channels.
        }
    }

    for (let i = 0; i < CHANNEL_COUNT; i++) {
        device.addChannel(
            CHANNELS[i],
            LED_LIMIT_PER_CHANNEL
        );
    }
}


function sendDirectRgbFrame() {
    /*
     * Build the frame with fixed 11-slot regions for all ten physical ports.
     * This prevents component LED counts from shifting later port offsets.
     */
    const frameColors = collectDirectRgbColors();

    for (
        let packetIndex = 0;
        packetIndex < DIRECT_STREAM_PACKET_COUNT;
        packetIndex++
    ) {
        const start =
            packetIndex *
            DIRECT_STREAM_LEDS_PER_PACKET;

        const packetColors =
            frameColors.slice(
                start,
                start +
                DIRECT_STREAM_LEDS_PER_PACKET
            );

        sendDirectRgbPacket(
            packetIndex + 1,
            packetColors
        );
    }

    /*
     * Avoid flooding the console. Log once per ~30 Render() calls.
     */
    if (
        isDebugLoggingEnabled() &&
        (frameCounter % 30) === 0
    ) {
        let activeCount = 0;

        for (
            let i = 0;
            i < frameColors.length;
            i++
        ) {
            const color = frameColors[i];

            if (
                color[0] !== 0 ||
                color[1] !== 0 ||
                color[2] !== 0
            ) {
                activeCount++;
            }
        }

        device.log(
            "[AsiaHorse] Direct RGB frame sent: " +
            DIRECT_STREAM_PACKET_COUNT +
            " packets, " +
            activeCount +
            "/" +
            DIRECT_STREAM_LED_LIMIT +
            " non-black slots."
        );
    }
}


function collectDirectRgbColors() {
    const output = [];

    /*
     * Physical stream layout:
     *
     * Port 01 -> slots   0..10
     * Port 02 -> slots  11..21
     * Port 03 -> slots  22..32
     * Port 04 -> slots  33..43
     * Port 05 -> slots  44..54
     * Port 06 -> slots  55..65
     * Port 07 -> slots  66..76
     * Port 08 -> slots  77..87
     * Port 09 -> slots  88..98
     * Port 10 -> slots  99..109
     * Padding -> slots 110..119
     *
     * Unconfigured ports still reserve their 11 slots so later ports keep
     * their physical offsets.
     */
    for (
        let port = 0;
        port < DIRECT_PORT_COUNT;
        port++
    ) {
        const channel =
            device.channel(
                CHANNELS[port]
            );

        if (!channel) {
            appendBlackColors(
                output,
                DIRECT_SLOTS_PER_PORT
            );

            continue;
        }

        const portColors =
            sampleChannelToFixedSlots(
                channel,
                DIRECT_SLOTS_PER_PORT
            );

        for (
            let i = 0;
            i < portColors.length;
            i++
        ) {
            output.push(
                portColors[i]
            );
        }
    }

    /*
     * Pad the unused tail of the 120-slot transport frame with black.
     */
    appendBlackColors(
        output,
        DIRECT_STREAM_LED_LIMIT -
        output.length
    );

    return output;
}


function sampleChannelToFixedSlots(
    channel,
    targetSlotCount
) {
    const ledCount =
        channel.LedCount();

    if (ledCount <= 0) {
        return createBlackColors(
            targetSlotCount
        );
    }

    const colorData =
        channel.getColors(
            "Seperate"
        );

    if (
        !colorData ||
        colorData.length < 3
    ) {
        return createBlackColors(
            targetSlotCount
        );
    }

    const red =
        colorData[0] || [];

    const green =
        colorData[1] || [];

    const blue =
        colorData[2] || [];

    const sourceCount =
        Math.min(
            ledCount,
            red.length,
            green.length,
            blue.length
        );

    if (sourceCount <= 0) {
        return createBlackColors(
            targetSlotCount
        );
    }

    const output = [];

    /*
     * Resample the SignalRGB component to the 11 physical transport slots
     * for this hub port.
     *
     * This keeps the whole effect visible even when the selected SignalRGB
     * component declares a different LED count (for example 12 or 16 LEDs),
     * without moving the start offset of the next physical port.
     */
    for (
        let slot = 0;
        slot < targetSlotCount;
        slot++
    ) {
        const sourceIndex =
            targetSlotCount <= 1
                ? 0
                : Math.round(
                    (
                        slot /
                        (
                            targetSlotCount -
                            1
                        )
                    ) *
                    (
                        sourceCount -
                        1
                    )
                );

        output.push([
            clampByte(
                red[sourceIndex]
            ),

            clampByte(
                green[sourceIndex]
            ),

            clampByte(
                blue[sourceIndex]
            )
        ]);
    }

    return output;
}


function createBlackColors(count) {
    return Array.from(
        {
            length:
                count
        },

        () => [
            0,
            0,
            0
        ]
    );
}

function sendDirectRgbPacket(
    packetIndex,
    colors20
) {
    /*
     * Direct RGB packet layout:
     *
     * byte 0     = 0x88
     * byte 1     = total packet count
     * byte 2     = 1-based packet index
     * byte 3..62 = 20 RGB values
     * byte 63    = additive checksum of bytes 0..62
     */
    const packet = [
        0x88,
        DIRECT_STREAM_PACKET_COUNT,
        packetIndex & 0xFF
    ];

    for (
        let i = 0;
        i < DIRECT_STREAM_LEDS_PER_PACKET;
        i++
    ) {
        const color =
            colors20[i] ||
            [0, 0, 0];

        packet.push(
            clampByte(color[0]),
            clampByte(color[1]),
            clampByte(color[2])
        );
    }

    /*
     * At this point packet.length must be 63.
     */
    packet.push(
        checksum(packet)
    );

    /*
     * SignalRGB HID writes include report ID 0 as byte zero.
     */
    const report = [0x00];

    for (
        let i = 0;
        i < 64;
        i++
    ) {
        report.push(
            packet[i] & 0xFF
        );
    }

    device.write(
        report,
        65
    );
}


function renderNativeDebugMode(force) {
    const mode =
        getCurrentDebugMode();

    if (mode === "Live") {
        return;
    }

    for (
        let port = 0;
        port < CHANNEL_COUNT;
        port++
    ) {
        const channel =
            device.channel(
                CHANNELS[port]
            );

        if (!channel) {
            continue;
        }

        const ledCount =
            channel.LedCount();

        /*
         * Leave unconfigured outputs untouched.
         */
        if (ledCount <= 0) {
            continue;
        }

        const profile =
            buildNativeDebugProfile(
                mode
            );

        if (
            !force &&
            nativePortInitialized[port] &&
            profilesEqual(
                nativeLastProfiles[port],
                profile
            )
        ) {
            continue;
        }

        sendPortProfile(
            port,
            profile.selector,
            profile.colors
        );

        nativeLastProfiles[port] =
            cloneProfile(profile);

        nativePortInitialized[port] =
            true;
    }
}


function buildNativeDebugProfile(mode) {
    if (
        mode ===
        "Native Rainbow Test"
    ) {
        return {
            selector:
                MODE_NATIVE_RAINBOW,

            colors:
                cloneColors(
                    CAPTURED_NATIVE_RAINBOW
                )
        };
    }

    /*
     * Known-good solid-red FE05 profile.
     */
    return createSolidProfile(
        [255, 0, 0]
    );
}


function createSolidProfile(color) {
    const safeColor = [
        clampByte(color[0]),
        clampByte(color[1]),
        clampByte(color[2])
    ];

    return {
        selector:
            MODE_SOLID,

        colors:
            Array.from(
                {
                    length:
                        PALETTE_SLOTS
                },

                () =>
                    safeColor.slice()
            )
    };
}


function sendPortProfile(
    port,
    selector,
    colors12
) {
    const body =
        PORT_PROFILE_PREFIX.slice();

    body[2] =
        port &
        0xFF;

    body[9] =
        selector &
        0xFF;

    for (
        let i = 0;
        i < PALETTE_SLOTS;
        i++
    ) {
        const color =
            colors12[i] ||
            [0, 0, 0];

        body.push(
            clampByte(color[0]),
            clampByte(color[1]),
            clampByte(color[2])
        );
    }

    if (
        isDebugLoggingEnabled()
    ) {
        device.log(
            "[AsiaHorse] Native FE05: mode=" +
            getCurrentDebugMode() +
            " port=" +
            port +
            " selector=0x" +
            selector
                .toString(16)
                .padStart(2, "0")
        );
    }

    sendNativeCommand(
        body
    );
}


function enterSoftwareControlMode() {
    sendNativeCommand(
        [0xFD, 0x01]
    );

    device.pause(2);
}


function sendNativeKeepAlive() {
    sendNativeCommand(
        [0x00]
    );
}


function sendNativeCommand(body) {
    /*
     * Captured native framing:
     *
     * 52 42
     * [logical length]
     * 00
     * [body...]
     * [checksum]
     *
     * The payload is then padded to exactly 64 bytes.
     */
    const packet = [
        0x52,
        0x42,
        0x00,
        0x00
    ];

    for (
        let i = 0;
        i < body.length;
        i++
    ) {
        packet.push(
            body[i] &
            0xFF
        );
    }

    /*
     * Logical length includes the checksum byte.
     */
    packet[2] =
        (
            packet.length +
            1
        ) &
        0xFF;

    packet.push(
        checksum(packet)
    );

    while (
        packet.length <
        64
    ) {
        packet.push(
            0x00
        );
    }

    const report = [0x00];

    for (
        let i = 0;
        i < 64;
        i++
    ) {
        report.push(
            packet[i] &
            0xFF
        );
    }

    device.write(
        report,
        65
    );
}


function invalidateNativeProfileCache() {
    nativeLastProfiles = [];
    nativePortInitialized = [];
}


function getCurrentDebugMode() {
    if (
        typeof debugMode === "undefined" ||
        !debugMode
    ) {
        return "Live";
    }

    return String(
        debugMode
    );
}


function isDebugLoggingEnabled() {
    if (
        typeof debugLog ===
        "undefined"
    ) {
        return false;
    }

    return (
        debugLog === true ||
        debugLog === 1 ||
        debugLog === "1" ||
        debugLog === "true"
    );
}


function appendBlackColors(
    target,
    count
) {
    for (
        let i = 0;
        i < count;
        i++
    ) {
        target.push(
            [0, 0, 0]
        );
    }
}


function checksum(bytes) {
    let sum = 0;

    for (
        let i = 0;
        i < bytes.length;
        i++
    ) {
        sum =
            (
                sum +
                (
                    bytes[i] &
                    0xFF
                )
            ) &
            0xFF;
    }

    return sum;
}


function profilesEqual(
    a,
    b
) {
    if (
        !a ||
        !b ||
        a.selector !==
            b.selector ||
        a.colors.length !==
            b.colors.length
    ) {
        return false;
    }

    for (
        let i = 0;
        i < a.colors.length;
        i++
    ) {
        const ca =
            a.colors[i];

        const cb =
            b.colors[i];

        if (
            ca[0] !== cb[0] ||
            ca[1] !== cb[1] ||
            ca[2] !== cb[2]
        ) {
            return false;
        }
    }

    return true;
}


function cloneProfile(profile) {
    return {
        selector:
            profile.selector,

        colors:
            cloneColors(
                profile.colors
            )
    };
}


function cloneColors(colors) {
    return colors.map(
        color =>
            color.slice()
    );
}


function clampByte(value) {
    const number =
        Number(value);

    if (
        !Number.isFinite(
            number
        )
    ) {
        return 0;
    }

    return Math.max(
        0,
        Math.min(
            255,
            Math.round(
                number
            )
        )
    );
}
